FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip3 install --no-cache-dir --upgrade pip \
 && pip3 install --no-cache-dir --upgrade pip setuptools wheel

RUN pip3 install --no-cache-dir -r ./requirements.txt

# COPY ./data /app/data
COPY ./test_project /app/test_project
COPY ./src /app/src
COPY .env /app/.env

ENV RUN_IN_DOCKER=1

CMD ["python", "./src/init_vectorstores.py"]