FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip3 install --no-cache-dir --upgrade pip \
 && pip3 install --no-cache-dir --upgrade pip setuptools wheel \
 && pip3 install --no-cache-dir -r ./requirements.txt \
 && pip3 install watchdog==3.0.0

COPY ./src /app/src
COPY .env /app/.env

ENV RUN_IN_DOCKER=1

CMD ["python", "-m", "src.run_implementation_agent"] 