version: '3.8'

services:
  persistence_pg_db:
    image: postgres:16
    container_name: ${PERSISTENCE_PG_CONTAINER}
    environment:
      POSTGRES_USER: ${PERSISTENCE_PG_USER}
      POSTGRES_PASSWORD: ${PERSISTENCE_PG_PASSWORD}
      POSTGRES_DB: ${PERSISTENCE_PG_DB}
    ports:
      - "${PERSISTENCE_PG_PORT}:5432"
    volumes:
      - ./volumes/${PERSISTENCE_PG_CONTAINER}-data:/var/lib/postgresql/data

  pgvector-docs:
    image: pgvector/pgvector:pg16
    container_name: ${RETRIEVER_DB}
    environment:
      POSTGRES_USER: ${RETRIEVER_USER}
      POSTGRES_PASSWORD: ${RETRIEVER_PASSWORD}
      POSTGRES_DB: ${RETRIEVER_DB}
    ports:
      - "${RETRIEVER_PORT}:5432"
    volumes:
      - ./volumes/${RETRIEVER_DB}-data:/var/lib/postgresql/data

  task_splitting_agent:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: task_splitting_agent
    environment:
      - AGENT_TYPE=task_splitter
    volumes:
      - ./arch:/app/arch:ro
      - ./test_project:/app/test_project
      - ./logs:/app/logs
    depends_on:
      - persistence_pg_db
      - pgvector-docs
    command: ["python", "-m", "src.agents.task_agent"]
    restart: on-failure
    healthcheck:
      test: python -c "import os; exit(0 if os.path.exists('/app/logs/task_agent.log') else 1)"
      interval: 10s
      timeout: 5s
      retries: 3

  code_generation_agent:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: code_generation_agent
    environment:
      - AGENT_TYPE=code_generator
    volumes:
      - ./arch:/app/arch:ro
      - ./test_project:/app/test_project
      - ./logs:/app/logs
    depends_on:
      - persistence_pg_db
      - pgvector-docs
      - task_splitting_agent
    command: ["python", "-m", "src.agents.code_agent"]
    restart: on-failure
    healthcheck:
      test: python -c "import os; exit(0 if os.path.exists('/app/logs/code_agent.log') else 1)"
      interval: 10s
      timeout: 5s
      retries: 3

  code_review_agent:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: code_review_agent
    environment:
      - AGENT_TYPE=code_reviewer
    volumes:
      - ./arch:/app/arch:ro
      - ./test_project:/app/test_project:ro  # только для чтения
      - ./logs:/app/logs
    depends_on:
      - persistence_pg_db
      - pgvector-docs
      - code_generation_agent
    command: ["python", "-m", "src.agents.review_agent"]
    restart: on-failure
    healthcheck:
      test: python -c "import os; exit(0 if os.path.exists('/app/logs/review_agent.log') else 1)"
      interval: 10s
      timeout: 5s
      retries: 3

  agent_endpoint:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: agent_endpoint
    ports:
      - "8000:8000"
    depends_on:
      - persistence_pg_db
      - pgvector-docs
      - task_splitting_agent
      - code_generation_agent
      - code_review_agent
    volumes:
      - ./arch:/app/arch:ro
      - ./test_project:/app/test_project
      - ./logs:/app/logs
    restart: on-failure
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info"]
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

